spring.datasource.url=jdbc:postgresql://localhost:5432/Care_Plus
spring.datasource.username=luquian
spring.datasource.password=123456789
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect